"""
Django settings for kitaluro project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Carga variables de entorno desde .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-lmh&7!%ru4a!t$l)an3%t14#9%udo=m*pru)qc%yw$kzmj@j29',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Detectar si estamos en Railway
IS_RAILWAY = os.environ.get('RAILWAY_ENVIRONMENT_NAME') is not None

ALLOWED_HOSTS = [
    'kitaluro-production.up.railway.app',
    'www.kitaluro.com',
    '.up.railway.app',
    '127.0.0.1',
    'localhost',
]


CSRF_TRUSTED_ORIGINS = [
    'https://kitaluro-production.up.railway.app',
    'https://*.up.railway.app',
]

# Seguridad de cookies — solo activar con HTTPS real (Railway)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_SSL_REDIRECT = False  # Railway ya maneja SSL en el proxy
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'productos',
    'usuarios',
    'kitaluro',
]

# Agregar cloudinary si está configurado (Railway/producción)
if os.environ.get('CLOUDINARY_CLOUD_NAME'):
    INSTALLED_APPS.insert(6, 'cloudinary_storage')
    INSTALLED_APPS.insert(7, 'cloudinary')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kitaluro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'kitaluro' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kitaluro.context_processors.brand_logos',
                'kitaluro.context_processors.nav_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'kitaluro.wsgi.application'


# =============================================================================
# DATABASE — usa DATABASE_URL en Railway, SQLite en local
# =============================================================================

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # En desarrollo local no requerir SSL, en producción sí
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG  # Solo requiere SSL en producción
        )
    }
else:
    # Configuración local con SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC FILES — WhiteNoise (CSS, JS, imágenes, vídeo hero, logos marcas)
# =============================================================================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# En Railway usar CompressedManifest, en local usar básico de WhiteNoise
if IS_RAILWAY:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# =============================================================================
# MEDIA FILES — Configuración según entorno
# =============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Si Cloudinary está configurado, usarlo (Railway/producción)
if os.environ.get('CLOUDINARY_CLOUD_NAME'):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
    }

    STORAGES = {
        # default used by FileField/ImageField
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage"
        },
        # optional: si quieres subir estáticos también a Cloudinary
        "staticfiles": {
            "BACKEND": "cloudinary_storage.storage.StaticHashedCloudinaryStorage"
        }
    }
else:
    # En local usar almacenamiento de archivos estándar de Django
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Image optimization settings
IMAGE_QUALITY = 90
MAX_IMAGE_SIZE = (1200, 1200)
THUMBNAIL_SIZE = (300, 300)

# Allowed image formats
ALLOWED_IMAGE_FORMATS = ['JPEG', 'JPG', 'PNG', 'WEBP']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CACHE — Redis si está configurado, sino sesiones en BD
# =============================================================================

REDIS_URL = os.environ.get("REDIS_URL")

if REDIS_URL:
    # Redis si está disponible
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    # Sesiones en base de datos (más simple y funciona siempre)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'