# Generated by Django 5.2.4 on 2025-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único del producto (se genera automáticamente)', max_length=100, unique=True),
        ),
    ]
