# Generated by Django 5.2.4 on 2025-12-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_estatus_proveedor_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
