# Generated by Django 5.2.4 on 2025-12-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
        migrations.DeleteModel(
            name='MediaProducto',
        ),
    ]
