# Generated by Django 5.2.4 on 2025-12-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_mediaproducto_producto_delete_imagenproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='garantia',
            field=models.TextField(blank=True, help_text='Detalles de la garantía del producto', verbose_name='Garantía'),
        ),
    ]
